M48
; DRILL file {KiCad 9.0.6} date 2026-03-25T23:27:07+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-25T23:27:07+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.600
%
G90
G05
T1
X115.0Y-105.0
T2
X112.7Y-115.5
X116.3Y-115.5
M30
